# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ece652ea44123ee6e97cc21519e54c81082246f32b029b68eeb4f498be47d7be26755b1f03921c7e242912091fcfa8748f4dba9d999f390f830233897acc12ac

test:
  secret_key_base: be72d8146a6238bbcf5e3c0413658930fd7eae1f70839b01adc25a4d8d4a3e022b2dcb6a21c46a0c58fe430124cbef3b800856d783346b39fb9c4c372dd31fea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
